### ISSUE TITLE
执行settings属性命令不会生效

### ISSUE THREAD

**Issue by wkbin** [xxinPro/AdbShellUtils#3]
比如执行settings put secure reduce_bright_colors_activated 1，会报错java.io.IOException: Cannot run program "su": error=13, Permission denied

**Comment by xxinPro** [comment]
平时较少看issue，抱歉
从错误信息上看，你应该是执行了su命令吧，adb执行settings是没有问题的，回复你之前刚刚试了settings put secure reduce_bright_colors_activated 1

**Comment by wkbin** [comment]
十分感谢，解决了我的问题
